name: Home
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - name: Checkout theme repo
        uses: actions/checkout@main
        with:
          repository: conholdate/total.conholdate.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: latest
          extended: true
      - name: Build Home
        run: hugo -b "https://total.conholdate.com" --cleanDestinationDir --minify --templateMetrics --templateMetricsHints --enableGitInfo
      - name: Deploy Home to S3
        run: hugo deploy --maxDeletes=0 --target "${{ github.event.inputs.environment }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
