name: Hugo (Language)
run-name: Hugo (${{ github.event.inputs.language }} - ${{ github.event.inputs.bucket }})

on:
  workflow_dispatch:
    inputs:
      language:
        description: Language
        type: string
      bucket:
        description: Deployment Bucket
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@main
        with:
          repository: conholdate/products.conholdate.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true
      - uses: actions/setup-node@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS }}
          aws-region: us-west-2

      - name: Configure Build Language
        run: |
          if [ "${{ github.event.inputs.language }}" == "ar" ]; then
            echo "HUGO_DISABLELANGUAGES=de fr zh ru tr pt es ja sv it da el iw ko af bg et pl nl th hi id cs fa fi hu ms uk vi no ca fil hr he" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.language }}" == "de" ]; then
            echo "HUGO_DISABLELANGUAGES=fr zh ru tr pt ar es ja sv it da el iw ko af bg et pl nl th hi id cs fa fi hu ms uk vi no ca fil hr he" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.language }}" == "en" ]; then
            echo "HUGO_DISABLELANGUAGES=de fr zh ru tr pt ar es ja sv it da el iw ko af bg et pl nl th hi id cs fa fi hu ms uk vi no ca fil hr he" >> $GITHUB_ENV
          fi
      - name: Build
        run: hugo --minify --enableGitInfo

      - name: Upload to ${{ github.event.inputs.bucket }} bucket
        run: aws s3 sync public s3://${{ github.event.inputs.bucket }}
