name: Hugo Segment
run-name: Hugo (${{ github.event.inputs.segment }} - ${{ github.event.inputs.environment }})

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deployment Environment
        type: environment
        default: staging
        required: true
      segment:
        description: Hugo Segment
        type: string
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@main
        with:
          repository: conholdate/products.conholdate.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true
      - uses: actions/setup-node@v4
      - name: Build
        run: hugo --environment "${{ github.event.inputs.environment }}" --minify --enableGitInfo --printMemoryUsage --renderSegments "${{ github.event.inputs.segment }}"
      - name: Deploy
        run: hugo deploy --maxDeletes=0 --environment "${{ github.event.inputs.environment }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
