name: New Build & Deploy .NET for All Languages
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true 

jobs:
  build-langs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      max-parallel: 2 
      matrix:
        # Provide all the languages you want to build in parallel
        language: [en, fr, zh, ru, tr, pt, ar, es, ja, de, sv, it, da, el, ko, pl, th, id, fa, vi, he]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: conholdate/products.conholdate.com
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          # Upgraded Hugo version
          hugo-version: '0.124.1'
          extended: true 

      - name: Install Node dependencies
        run: npm install

      - name: Configure environment (language + .NET platform)
        env:
          CONFIGURE_ONE_PLATFORM: net
          CONFIGURE_ONE_LANGUAGE: ${{ matrix.language }}
        run: |
          # Ensure your splitbyplatform.js script filters content to the current language and .NET platform
          npm run splitbyplatform

      - name: Build ${{ matrix.language }}
        run: |
          if [ "${{ matrix.language }}" = "en" ]; then
            echo "Building English version (includes theme assets and .NET content)..."
            hugo --minify --cleanDestinationDir -b "https://products.conholdate.com" --verbose
            mv public public-en-full
            tar -cf public-en-full.tar public-en-full
          else
            echo "Building ${{ matrix.language }} version (only .NET content)..."
            hugo --minify --cleanDestinationDir -b "https://products.conholdate.com" --verbose
            mv public public-${{ matrix.language }}-content
            tar -cf public-${{ matrix.language }}-content.tar public-${{ matrix.language }}-content
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-${{ matrix.language }}
          path: |
            public-en-full.tar
            public-${{ matrix.language }}-content.tar
          if-no-files-found: ignore

  combine-and-deploy:
    runs-on: ubuntu-latest
    needs: build-langs
    steps:
      - name: Checkout for final structure
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: all
          path: artifacts

      - name: Combine all languages
        run: |
          mkdir final
          # 1) Extract English full build (includes theme assets + English .NET content)
          tar -xf artifacts/public-en-full.tar
          mv public-en-full final/public

          # 2) Extract each non‑English partial artifact & merge (including Arabic)
          for lang in fr zh ru es de it ar; do
            tarfile="artifacts/public-$lang-content.tar"
            if [ -f "$tarfile" ]; then
              tar -xf "$tarfile"
              rsync -a public-$lang-content/ final/public/
              rm -rf public-$lang-content
            fi
          done

      - name: Verify final structure
        run: ls -R final/public

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
        run: |
          aws s3 sync final/public/ s3://products.conholdate.com --delete
          # Or adapt if using 'hugo deploy'
