name: Products-de
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Build environment'
        type: environment
        default: staging
        required: true 
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}   
    
    steps:
      - name: Checkout theme repo
        uses: actions/checkout@v3
        with:
          repository: conholdate/products.conholdate.com
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true  # Fetch hugo theme
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 0.101.0
          extended: true  

      - name: Build products.conholdate.com
        run: hugo --config config-de.toml --minify

      - name: Deploy products.conholdate.com to S3
        run: hugo deploy --target "${{ github.event.inputs.environment }}" --maxDeletes=0
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS }}
